# Generated by Django 3.1.2 on 2020-11-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=5)),
                ('icao', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gps', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_type', models.CharField(max_length=100)),
                ('airport_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('iso_region', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('gps_code', models.CharField(max_length=100)),
                ('iata', models.CharField(max_length=100)),
                ('altitude', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('local_code', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
            ],
        ),
    ]
