# Generated by Django 3.1.2 on 2020-11-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport1',
            name='iata',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airport1',
            name='icao',
            field=models.CharField(max_length=100),
        ),
    ]
